all : context0.c context1.c context2.c context3.c context_sol.c 
		gcc -w -g context0.c -o context0
		gcc -w -g context1.c -o context1
		gcc -w -g context2.c -o context2
		gcc -w -g context3.c -o context3
		gcc -w -g context_sol.c -o context_sol
clean :
		rm context0 context1 context2 context3 context_sol

